// <auto-generated />
using InventoryManagmentSystem.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagmentSystem.Migrations
{
    [DbContext(typeof(ApplecationDBContext))]
    partial class ApplecationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagmentSystem.Shared.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Description A",
                            LowStockThreshold = 10,
                            Name = "Product A",
                            Price = 10.99m,
                            Quantity = 100
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Description B",
                            LowStockThreshold = 15,
                            Name = "Product B",
                            Price = 15.49m,
                            Quantity = 150
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Description C",
                            LowStockThreshold = 20,
                            Name = "Product C",
                            Price = 8.99m,
                            Quantity = 200
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Description D",
                            LowStockThreshold = 8,
                            Name = "Product D",
                            Price = 12.99m,
                            Quantity = 80
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Description E",
                            LowStockThreshold = 12,
                            Name = "Product E",
                            Price = 5.99m,
                            Quantity = 120
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Description F",
                            LowStockThreshold = 25,
                            Name = "Product F",
                            Price = 20.00m,
                            Quantity = 300
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Description G",
                            LowStockThreshold = 5,
                            Name = "Product G",
                            Price = 7.50m,
                            Quantity = 50
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Description H",
                            LowStockThreshold = 6,
                            Name = "Product H",
                            Price = 11.25m,
                            Quantity = 60
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Description I",
                            LowStockThreshold = 9,
                            Name = "Product I",
                            Price = 9.95m,
                            Quantity = 90
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Description J",
                            LowStockThreshold = 7,
                            Name = "Product J",
                            Price = 14.75m,
                            Quantity = 70
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
